//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanVien
{
    using System;
    using System.Collections.Generic;
    
    public partial class Luong
    {
        public int MaLuong { get; set; }
        public string MaNV { get; set; }
        public Nullable<decimal> LuongCoBan { get; set; }
        public Nullable<decimal> PhuCap { get; set; }
        public Nullable<decimal> Thuong { get; set; }
        public Nullable<decimal> KhauTru { get; set; }
        public Nullable<decimal> TongLuong { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
